apiVersion: v1
kind: Service
metadata:
  name: {{ include "fayaz.fullname" . }}
spec:
  selector:
    app: {{ include "fayaz.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
  type: {{ .Values.serviceType }}
